[package]
name = "zapp"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.5"
regex = "1.11.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
vfs = "0.12.0"

[dev-dependencies]
googletest = "0.13.0"
