[project]
authors = ["Abie Marshall <abiemarshall94@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "super-duper-octo-lamp"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"
clean = "cargo clean"
fmt = "cargo fmt"

[dependencies]
rust = ">=1.83.0,<1.84"
