name: Python Semantic Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4

      - name: Semantic Release | Install Python
        # https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html#examples
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
